version: '3'
services:
  frontend:
    image: nginx:latest
    restart: always
    container_name: privategpt-frontend
    ports:
      - "8501:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - privategpt_net
   
  backend:
    image: privategpt:backend
    restart: always
    container_name: privategpt-backend
    ports:
      - "8500:8000"
    networks: 
      - privategpt_net
networks:
  privategpt_net:
